repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
        exclude: infra/helm/.*\.yaml$
      - id: debug-statements
        exclude: test/
      - id: destroyed-symlinks
      - id: end-of-file-fixer
        exclude: test/
        files: \.(py|sh|rst|yml|yaml)$
      - id: mixed-line-ending
      - id: trailing-whitespace
        files: \.(py|sh|rst|yml|yaml)$
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.263"
    hooks:
      - id: ruff
        args: [--config, backend/pyproject.toml, --fix]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.367
    hooks:
      - id: pyright
        args: [--project, backend/pyproject.toml]
